//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPalm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetSheet_3F
    {
        public int Id { get; set; }
        public string MatrixCode { get; set; }
        public System.DateTime InputDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
